baseURL = 'https://marchoek.nl/'
locale = 'en-us'
title = "Marc's Dungeon"
theme = 'hugo-castle'

[params]
    siteRepo = 'https://github.com/BlyGuy/marchoek.nl/'

[taxonomies]
    tag = "tags"

[[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
weight = 10

[[menus.main]]
    name = 'Games'
    url = 'https://earlgreysuperior.itch.io/'
    weight = 11

[[menus.main]]
    name = 'Contact'
    pageRef = '/contact.html'
    weight = 29

[[menus.main]]
    name = 'Credits'
    pageRef = '/credits.html'
    weight = 30

[caches]
  [caches.images]
    dir = ':cacheDir/images'