baseURL = 'https://marchoek.nl/'
languageCode = 'en-us'
title = "Marc's Dungeon"
theme = 'hugo-castle'

[params]
    siteRepo = 'https://github.com/BlyGuy/marchoek.nl/'

[taxonomies]
    tag = "tags"

[caches]
  [caches.images]
    dir = ':cacheDir/images'